### ISSUE TITLE
Teensy 3.5 support - seems not to work even though 3.6 compatible

### ISSUE THREAD

**Issue by riwide** [dherrendoerfer/altair-8800-again#1]
I tried to build in standalone mode for my teensy 3.5 (by changing the  ID in host.h to accept my  3.5 rather than 3.6.
There were a lot of errors generated referring to leds and switches which made me question whether your branched tree still supports standalone mode.

I actually wanted teensy 4.1 support but thought getting 3.5 working first was a good idea.

Can you confirm your build woirks in standalone mode?

**Comment by dherrendoerfer** [comment]
At some point it certainly did support it, I did test it that way - I'll need to check.
It might be that it still requires the support libs to be present though.

**Comment by riwide** [comment]
Thanks, I would be pleased if you can confirm your own good build of a
standalone version at some point. Make sure I am not being daft.

No hurry, it is a long term hobby with plenty of other rabbit holes to go
down.

Cheers
Richard

**Comment by dherrendoerfer** [comment]
Yes, I can confirm that a build with STANDALONE 1 works for me.
The standalone flag does not turn anything off really, it just overrides the switches by what is received through serial. So you'll still need all the support libs.
Cheers,
Dirk

**Comment by riwide** [comment]
Thanks, I will give it another go.

Richard

**Comment by riwide** [comment]
I had a problem that the uvga and other required libraries were forgotten. Now that I have them in place  I can build further but fails with " host_teensy36.cpp:968: error: 'class uVGA' has no member named 'drawPixelNoSync'
     uvga.drawPixelNoSync(x,y,0xE0);", and I can find no implementation of 'drawPixelNoSync' in uvga.

**Comment by dherrendoerfer** [comment]
I fixed the missing function error in uVGA ... no idea where that went missing, my local copy is older than the git master branch. 
Hoping that it works now .... 
Cheers, 
Dirk

**Comment by riwide** [comment]
All working fine now, thanks
Richard
